apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smtp4dev-data
  namespace: opal-onprem
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp4dev
  namespace: opal-onprem
  labels:
    app: smtp4dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp4dev
  template:
    metadata:
      labels:
        app: smtp4dev
    spec:
      containers:
      - name: smtp4dev
        image: rnwood/smtp4dev:latest
        ports:
        - containerPort: 587
          name: smtp
          protocol: TCP
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        # SMTP Server Settings
        - name: ServerOptions__Port
          value: "465"
        - name: ServerOptions__HostName
          value: "0.0.0.0"
        - name: ServerOptions__AllowRemoteConnections
          value: "true"
        - name: ServerOptions__NumberOfMessagesToKeep
          value: "100"
        - name: ServerOptions__NumberOfSessionsToKeep
          value: "100"
        - name: ServerOptions__DisableIPv6
          value: "true"
        - name: ServerOptions__TlsMode
          value: "ImplicitTls"
        # AUTHENTICATION SETTINGS
        # Require authentication
        - name: ServerOptions__AuthenticationRequired
          value: "true"
        - name: ServerOptions__SmtpAllowAnyCredentials
          value: "false"
        - name: ServerOptions__SecureConnectionRequired
          value: "false"
        # Auth types allowed
        - name: ServerOptions__SmtpEnabledAuthTypesWhenSecureConnection
          value: "PLAIN,LOGIN"
        - name: ServerOptions__SmtpEnabledAuthTypesWhenNotSecureConnection
          value: "PLAIN,LOGIN"

        # Define users (mimicking SparkPost)
        # User 0 - SparkPost-like credentials
        - name: ServerOptions__Users__0__Username
          value: "SMTP_Injection"  # Mimicking SparkPost username
        - name: ServerOptions__Users__0__Password
          value: "password"  # Mimicking API key
        - name: ServerOptions__Users__0__DefaultMailbox
          value: "Default"
        # Web UI Settings
        - name: ServerOptions__BasePath
          value: "/"
        volumeMounts:
        - name: data
          mountPath: /smtp4dev
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: smtp4dev-data
---
apiVersion: v1
kind: Service
metadata:
  name: smtp4dev
  namespace: opal-onprem
  labels:
    app: smtp4dev
spec:
  type: ClusterIP
  selector:
    app: smtp4dev
  ports:
  - name: smtp
    port: 465
    targetPort: 465
    protocol: TCP
  - name: smtpalternative
    port: 25
    targetPort: 25
    protocol: TCP
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
# Optional: NodePort service for easier web UI access
apiVersion: v1
kind: Service
metadata:
  name: smtp4dev-ui
  namespace: opal-onprem
  labels:
    app: smtp4dev
spec:
  type: NodePort
  selector:
    app: smtp4dev
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30025  # Access UI at any-node-ip:30025